baseURL: "https://jhoncf.github.io"
languageCode: "en-us"
title: "Jhonatas Faria"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Jhonatas Faria"
  description: Bem vindo ao meu site pessoal
  # staticPath: ""  # The path to serve the static files from
  favicon: "/favicon.ico"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Jhonatas Faria" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Olá, sou"
    title: "Jhonatas Faria"
    subtitle: "Gestão de Tecnologia - SRE - DevOps - Engenharia de Software - Consultor"
    content: "Sou um analista de sistemas, desenvolvedor, evangelista DevOps e arquiteto cloud com mais de 12 anos de experiência em tecnologia da informação, especializado em soluções de gestão para negócios recorrentes. Possuo as certificações EXIN DevOps e AWS Solutions Architect, evidenciando minhas habilidades técnicas e estratégicas."
    image: /images/jhonatas.jpeg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jhoncf
        - icon: fa fa-link
          url: https://linktr.ee/jhonatascf

  # About
  about:
    enable: true
    title: "Sobre Mim"
    image: "/images/me.png"
    content: |-
      Na minha trajetória, tenho liderado equipes de DevOps, Segurança e Compliance, com foco em arquitetura AWS. Sou encarregado de implementar e aprimorar normas de PCI, Segurança da Informação, LGPD e Compliance, integrando esses aspectos com os princípios DevOps e soluções de cloud. Meu papel central é assegurar a excelência, eficiência, segurança e conformidade dos serviços e produtos, visando sempre a satisfação dos clientes e parceiros. Apaixonado por Linux e tecnologias de cloud, estou sempre em busca de novidades e tendências do mercado para manter a inovação constante.
      <br>      <br>

    skills:
      enable: true
      title: "Aqui estão algumas das minhas habilidades:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "PHP"
        - "AWS"
        - "OCI"
        - "Docker"
        - "Kubernetes"
        - "Jenkins"
        - "Git"
        - "Linux"
        - "Windows"
        - "Python"
        - "Bash"
        - "Ansible"
        - "Terraform"
        - "Shell Script"
        - "SQL"
        - "NoSQL"
        - "API"

  # Experience
  experience:
    enable: true
    title: "Experiência Profissional"
    items:
      - job: "Gerente Sênior de Tecnologia da Informação"
        company: "Superlógica"
        companyUrl: "https://superlogica.com"
        date: "Fev 2017 - atualmente"
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: "Líder de DevOps, Segurança e Compliance e atuando também com arquitetura AWS."

      - job: "Software Engineer"
        company: "Dcide"
        companyUrl: "https://dcide.com.br"
        date: "Mar 2015 - Jan 2017"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Software Developer"
        company: "Webzero"
        companyUrl: "https://webzero.com.br"
        date: "Out 2012 - Jan 2015"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Analista de suporte"
        company: "Devel IT"
        companyUrl: "https://www.develsistemas.com.br/"
        date: "Jan 2012 - Set 2012"
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      
  # Education
  education:
    enable: true
    title: "Formação Acadêmica"
    index: false
    items:
      - title: "MBA - Gestão de Tecnologia da Informação"
        school:
          name: "Fundação Getúlio Vargas"
          url: "https://fgv.br"
        date: "2023 - 2024"
      - title: "Bacharelado em Analise de Sistemas e Tecnologia da Informação"
        school:
          name: "FATEC"
          url: "https://www.fatecourinhos.edu.br/"
        date: "2010 - 2014"

  # Achievements
  achievements:
    enable: true
    title: "Certificações"
    items:
      - title: AWS Solutions Architect Associate
      - title: Devops Professional - EXIN
        url: "https://app.exeed.pro/badge/15091"

  # projects
  
  #Contact
  contact:
    enable: true
    title: "Contato"
    content: "Se você deseja entrar em contato comigo, por favor, clique no link abaixo!"
    btnName: Me envie um e-mail
    btnLink: mailto:jhonatas.cf@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/jhoncf
      linkedin: https://www.linkedin.com/in/jhonatas-faria/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
